### ISSUE TITLE
Block size is not increasing after sending HEX over zagg network

### ISSUE THREAD

**Issue by Vishwas1** [zagg-protocol/zagg-core#7]
# Issue type
bug

# Version found
  *  `git rev-parse HEAD` : `2ca122cc168d03dd832c87f822f8dbeb3e4ecdee`
  *  `./stellar-core --version` : `v10.1.0-197-g2ca122c-dirty`
  * branch : `blockCommit`

# Issue description

Block size is not increasing.

# Issue recreation steps

- Run zagg-core
- Create HEX -> Use zagg-lab to send HEX using MarkAccount operation
- Send the XDR using tx route
- Check the block size : It increased.
- Stop the Zagg-core
- Re-Run the zagg-core and check the block size again - It got reverted back.

**Comment by helloravi** [comment]
https://github.com/zagg-protocol/zagg-core/commit/b8b58735bb88ed7a5b733565135d4ab2970dcc92

Issue has been resolved
